# Generated by Django 3.2.20 on 2023-09-03 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20230902_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='time_of_creat',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 20, 20, 32, 499324)),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'division')},
        ),
    ]
